In [1]:
import pandas as pd
import numpy as np

In [2]:
s = pd.Series(['a 1', 'b 2', 'c 3'])

In [3]:
s.str.extract(r'([ab])(\d)')

0    1
0  NaN  NaN
1  NaN  NaN
2  NaN  NaN

In [4]:
s.str.extract(r'([ab])?(\d)')

0  1
0  NaN  1
1  NaN  2
2  NaN  3

In [5]:
s.str.extract(r'([\d])')

0
0  1
1  2
2  3

In [6]:
s.str.extract(r'([abc])(\d)')

0    1
0  NaN  NaN
1  NaN  NaN
2  NaN  NaN

In [7]:
s.str.extract(r)

NameError: name 'r' is not defined

In [8]:
np.zeros((10,))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((4))

array([0., 0., 0., 0.])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.empty((4,3))

array([[4.6539189e-310, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])