In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
color = sns.color_palette()
sns.set_style('darkgrid')
import warnings

def ignore_warn(*args, **kwargs):
    pass
warnings.warn = ignore_warn

from scipy import stats
from scipy.stats import norm, skew

pd.set_option('display.float_format', lambda x: '{:.3f}'.format(x) )


In [3]:
items = pd.read_csv('./input/items.csv')
shops = pd.read_csv('./input/shops.csv')
cats = pd.read_csv('./input/item_categories.csv')
train = pd.read_csv('./input/sales_train.csv')
test = pd.read_csv('./input/test.csv')

In [4]:
train.head()

date  date_block_num  shop_id  item_id  item_price  item_cnt_day
0  02.01.2013               0       59    22154     999.000         1.000
1  03.01.2013               0       25     2552     899.000         1.000
2  05.01.2013               0       25     2552     899.000        -1.000
3  06.01.2013               0       25     2554    1709.050         1.000
4  15.01.2013               0       25     2555    1099.000         1.000

In [5]:
train.shape

(2935849, 6)

In [6]:
train['date_block_num'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [8]:
sales = train[train.date_block_num==0]

In [ ]:
plt.figure(figsize=(10,4))
plt.xlim(-100, 3000)
sns.boxplot(x=train.item_c)

In [9]:
sales

date  date_block_num  shop_id  item_id  item_price  item_cnt_day
0       02.01.2013               0       59    22154     999.000         1.000
1       03.01.2013               0       25     2552     899.000         1.000
2       05.01.2013               0       25     2552     899.000        -1.000
3       06.01.2013               0       25     2554    1709.050         1.000
4       15.01.2013               0       25     2555    1099.000         1.000
...            ...             ...      ...      ...         ...           ...
115685  19.01.2013               0       46       32     349.000         1.000
115686  18.01.2013               0       46       32     349.000         1.000
115687  26.01.2013               0       46       35     399.000         2.000
115688  31.01.2013               0       46      621     149.000         1.000
115689  07.01.2013               0       46       32     349.000         1.000

[115690 rows x 6 columns]

In [18]:
train = train[train.item_price > 1000]

In [19]:
train.shape

(662452, 6)

In [20]:
import  gc

In [21]:
gc.collect()

9903

In [22]:
train.head()

date  date_block_num  shop_id  item_id  item_price  item_cnt_day
3   06.01.2013               0       25     2554    1709.050         1.000
4   15.01.2013               0       25     2555    1099.000         1.000
25  27.01.2013               0       25     2609    1699.000         1.000
26  06.01.2013               0       25     2548    1708.950         1.000
29  06.01.2013               0       25     2515    1649.000         1.000

In [23]:
import time

In [24]:
ts = time.time()
matrix = []
cols = ['date_block_num', 'shop_id', 'item_id']


In [25]:
from itertools import product

In [27]:
for i in range(34):
    sales = train[train.date_block_num==i]
    matrix.append(np.array(list(product([i], sales.shop_id.unique(), sales.item_id.unique())), dtype='int16'))

In [29]:
matrix_df = pd.DataFrame(np.vstack(matrix), columns=cols)

In [32]:
matrix_df.head(100)

date_block_num  shop_id  item_id
0                0       25     2554
1                0       25     2555
2                0       25     2609
3                0       25     2548
4                0       25     2515
..             ...      ...      ...
95               0       25     1651
96               0       25     5261
97               0       25     5275
98               0       25     4988
99               0       25     5115

[100 rows x 3 columns]

In [31]:
matrix

[array([[    0,    25,  2554],
        [    0,    25,  2555],
        [    0,    25,  2609],
        ...,
        [    0,    45,  7889],
        [    0,    45,  2805],
        [    0,    45, 17722]], dtype=int16),
 array([[    1,    50,  3880],
        [    1,    50,  3879],
        [    1,    50,  3950],
        ...,
        [    1,    28, 15380],
        [    1,    28, 19954],
        [    1,    28, 13433]], dtype=int16),
 array([[   2,   41, 2319],
        [   2,   41, 2447],
        [   2,   41, 2446],
        ...,
        [   2,    5, 4809],
        [   2,    5, 5272],
        [   2,    5, 3325]], dtype=int16),
 array([[    3,    25,  8093],
        [    3,    25,  8094],
        [    3,    25,  7893],
        ...,
        [    3,    41, 16321],
        [    3,    41, 18587],
        [    3,    41, 20690]], dtype=int16),
 array([[    4,    27, 20783],
        [    4,    27, 20671],
        [    4,    27, 20596],
        ...,
        [    4,     5,  2637],
        [    4,     5,  2